import { Footer, Header, PurchaseButtons } from '../../site-chrome';

const samples=[['pagina_009.jpg','What you will find in this guide'],['pagina_023.jpg','Foundations of healthy hair'],['pagina_025.jpg','Conscious washing'],['pagina_026.jpg','Hair hydration'],['pagina_027.jpg','Nutrition and diet'],['pagina_028.jpg','Get to know your hair'],['pagina_029.jpg','A basic healthy routine'],['pagina_032.jpg','Hydrating hair mask'],['pagina_036.jpg','Heat protection'],['pagina_038.jpg','Hair nourishment'],['pagina_041.jpg','Care for color-treated hair'],['pagina_052.jpg','Recipe summary'],['pagina_070.jpg','Personalize your routine'],['pagina_078.jpg','Progress journal'],['pagina_082.jpg','Guide to reading labels'],['pagina_092.jpg','30-day plan']];

export default function EnglishBookPage(){return <main><Header lang="en" path="/el-libro"/>
  <section className="detailHero blushHero"><div className="wrap detailHeroGrid"><div><p className="eyebrow">Inside the book</p><h1>A visual, practical guide designed to revisit.</h1><p>Foundations, routines, ingredients, recipes, and tracking tools brought together in one book.</p><PurchaseButtons lang="en"/><a className="demoLink" href="/en/demo-libro">Read the free 30-page demo →</a></div><img className="bookCutout" src="/libro.jpg" alt="Cover of El Método Cabello Saludable"/></div></section>
  <section className="bookStats wrap"><div><strong>4</strong><span>practical sections</span></div><div><strong>90</strong><span>days of tracking</span></div><div><strong>3</strong><span>available formats</span></div></section>
  <section className="gallerySection wrap" id="interior"><div className="sectionTitle"><p className="eyebrow">Look inside</p><h2>A selection of pages from the book.</h2><p>A preview of its visual style and variety of content. The book pages themselves are presented in their original Spanish.</p></div><div className="bookGallery">{samples.map(([src,label])=><figure key={src}><img src={`/book-pages/${src}`} alt={label}/><figcaption>{label}</figcaption></figure>)}</div></section>
  <section className="buyStrip"><div className="wrap"><div><p className="eyebrow light">Choose your edition</p><h2>Amazon or Google Play Books.</h2><p>Printed book, Kindle, or Ebook.</p></div><PurchaseButtons lang="en"/></div></section><Footer lang="en"/>
</main>}
