import { Footer, Header, PurchaseButtons } from '../site-chrome';

const samples=[['pagina_009.jpg','Qué encontrarás en esta guía'],['pagina_023.jpg','Fundamentos del cabello saludable'],['pagina_025.jpg','Lavado consciente'],['pagina_026.jpg','Hidratación del cabello'],['pagina_027.jpg','Nutrición y alimentación'],['pagina_028.jpg','Conoce tu cabello'],['pagina_029.jpg','Rutina básica saludable'],['pagina_032.jpg','Mascarilla hidratante'],['pagina_036.jpg','Protección frente al calor'],['pagina_038.jpg','Nutrición del cabello'],['pagina_041.jpg','Cuidado para cabello teñido'],['pagina_052.jpg','Resumen de recetas'],['pagina_070.jpg','Personaliza tu rutina'],['pagina_078.jpg','Diario de progreso'],['pagina_082.jpg','Guía para leer etiquetas'],['pagina_092.jpg','Plan de 30 días']];

export default function LibroPage(){return <main><Header path="/el-libro"/>
  <section className="detailHero blushHero"><div className="wrap detailHeroGrid"><div><p className="eyebrow">Por dentro</p><h1>Una guía visual, práctica y hecha para volver a consultar.</h1><p>Fundamentos, rutinas, ingredientes, recetas y herramientas de seguimiento reunidos en un solo libro.</p><PurchaseButtons/><a className="demoLink" href="/demo-libro">Leer la demo gratuita de 30 páginas →</a></div><img className="bookCutout" src="/libro.jpg" alt="Portada del libro El Método Cabello Saludable"/></div></section>
  <section className="bookStats wrap"><div><strong>4</strong><span>bloques prácticos</span></div><div><strong>90</strong><span>días de seguimiento</span></div><div><strong>3</strong><span>formatos disponibles</span></div></section>
  <section className="gallerySection wrap" id="interior"><div className="sectionTitle"><p className="eyebrow">Mira el interior</p><h2>Algunas páginas del libro.</h2><p>Una selección para conocer su estilo visual y la variedad de contenidos.</p></div><div className="bookGallery">{samples.map(([src,label])=><figure key={src}><img src={`/book-pages/${src}`} alt={label}/><figcaption>{label}</figcaption></figure>)}</div></section>
  <section className="buyStrip"><div className="wrap"><div><p className="eyebrow light">Elige tu edición</p><h2>Amazon o Google Play Books.</h2><p>Libro impreso, Kindle o Ebook.</p></div><PurchaseButtons/></div></section><Footer/>
</main>}
