const kindle = 'https://kdp.amazon.com/amazon-dp-action/us/dualbookshelf.marketplacelink/B0HDKQTKZ9';
const paperback = 'https://kdp.amazon.com/amazon-dp-action/us/dualbookshelf.marketplacelink/B0HFHC2QL7';
const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Home() {
  return <main>
    <nav className="nav wrap" aria-label="Navegación principal"><a className="brand" href="#inicio"><span>YL</span> Yeney López-Pérez</a><div className="navlinks"><a href="#metodo">El método</a><a href="#autora">La autora</a><a className="navcta" href={paperback} target="_blank" rel="noreferrer">Comprar el libro</a></div></nav>
    <section className="hero" id="inicio"><div className="wrap heroGrid"><div className="heroCopy"><p className="eyebrow">Belleza consciente · Cuidado desde la raíz</p><h1>Tu cabello cuenta la historia de <em>cómo te cuidas.</em></h1><p className="lead">Descubre un método claro y amoroso para comprender tu cabello, crear hábitos saludables y recuperar la confianza en tu belleza natural.</p><div className="actions"><a className="button primary" href={paperback} target="_blank" rel="noreferrer">Comprar tapa blanda <Arrow /></a><a className="button ghost" href={kindle} target="_blank" rel="noreferrer">Leer en Kindle <Arrow /></a></div><p className="available"><span>✦</span> Disponible en Amazon en español</p></div><div className="heroVisual"><div className="sun"/><img className="book" src="/libro.jpg" alt="Portada de El Método Cabello Saludable, de Yeney López-Pérez"/><span className="botanical one">⌇</span><span className="botanical two">⌇</span></div></div></section>
    <section className="intro wrap" id="metodo"><div><p className="eyebrow">Guía completa en español</p><h2>Entiende, cuida y transforma tu cabello desde la raíz.</h2></div><div className="introText"><p><strong>El Método Cabello Saludable</strong> es una guía práctica para comprender mejor tu cabello, construir una rutina que tenga sentido para ti y tomar decisiones con más información, constancia y paciencia.</p><p>No promete resultados milagrosos ni presenta una única rutina como perfecta. Te ayuda a entender qué necesita tu cabello y por qué puede reaccionar de manera diferente a productos, hábitos e ingredientes.</p></div></section>
    <section className="pillars wrap"><article><span>01</span><i>◌</i><h3>Comprende</h3><p>Reconoce las características de tu cabello y aprende a escuchar lo que necesita.</p></article><article><span>02</span><i>♧</i><h3>Nutre</h3><p>Descubre hábitos e ingredientes que apoyan la salud capilar desde la raíz.</p></article><article><span>03</span><i>∞</i><h3>Transforma</h3><p>Construye una rutina sostenible que celebre tu textura y tu belleza auténtica.</p></article></section>
    <section className="inside wrap"><div><p className="eyebrow">Lo que encontrarás</p><h2>Conocimiento que puedes llevar a tu rutina.</h2></div><div className="insideList"><p><b>01</b><span><strong>Conoce tu cabello</strong>Formación, porosidad, ciclo natural y factores que influyen en su apariencia.</span></p><p><b>02</b><span><strong>Cuídalo con intención</strong>Lavado, hidratación, acondicionamiento e ingredientes explicados de forma sencilla.</span></p><p><b>03</b><span><strong>Distingue sus señales</strong>Diferencias entre caída y quiebre, y herramientas para observar cambios reales.</span></p><p><b>04</b><span><strong>Pasa a la práctica</strong>Recetas caseras accesibles, referencias científicas y un diario de progreso de 90 días.</span></p></div></section>
    <section className="quoteBand"><div className="wrap quoteGrid"><img src="/cabello.jpg" alt="Cabello largo y saludable de Yeney"/><blockquote><span>“</span><p>Cuando aprendes a cuidar tu cabello desde el conocimiento y el amor, no solo cambia su apariencia. Cambia la forma en que te miras.</p><cite>— Yeney López-Pérez</cite></blockquote></div></section>
    <section className="author wrap" id="autora"><div className="authorPhoto"><img src="/yeney.jpg" alt="Yeney López-Pérez, autora de El Método Cabello Saludable"/><span>Autora<br/>& guía</span></div><div className="authorCopy"><p className="eyebrow">Conoce a la autora</p><h2>Yeney<br/>López-Pérez</h2><p className="authorLead">Creadora de contenido y apasionada por el cuidado capilar.</p><p>Tras años de investigación, prueba y error, Yeney transformó su propio cabello. En el libro comparte también su experiencia personal con la caída asociada al hipotiroidismo, presentada como una vivencia individual y separada de aquello que cuenta con respaldo científico.</p><p>Su propósito es ayudarte a dejar atrás la improvisación y construir una rutina con conocimiento, intención y amor propio.</p></div></section>
    <section className="bookCta"><div className="wrap ctaGrid"><div><p className="eyebrow light">Tu nueva etapa comienza aquí</p><h2>Tu cabello es vida. Cuídalo desde la raíz.</h2><p>No se trata de tener el cabello perfecto. Se trata de conocerlo, cuidarlo y aprender a disfrutar de él.</p><div className="actions"><a className="button cream" href={kindle} target="_blank" rel="noreferrer">Leer en Kindle <Arrow /></a><a className="button outline" href={paperback} target="_blank" rel="noreferrer">Comprar tapa blanda <Arrow /></a></div></div><img src="/libro-portada.png" alt="El Método Cabello Saludable, disponible en Amazon"/></div></section>
    <footer className="wrap"><a className="brand" href="#inicio"><span>YL</span> Yeney López-Pérez</a><p>El Método Cabello Saludable</p><p>© 2026 Yeney López-Pérez</p></footer>
  </main>;
}
