import { Footer, Header, PurchaseButtons } from '../site-chrome';

export default function EnglishHome() {
  return <main>
    <Header lang="en" path="/"/>
    <section className="hero" id="home"><div className="wrap heroGrid"><div className="heroCopy"><p className="eyebrow">Conscious beauty · Care from the roots</p><h1>Your hair tells the story of <em>how you care for yourself.</em></h1><p className="lead">Discover a clear and caring method to understand your hair, build healthy habits, and regain confidence in your natural beauty.</p><PurchaseButtons lang="en"/><p className="available"><span>✦</span> Available on Amazon and Google Play Books</p></div><div className="heroVisual"><div className="sun"/><img className="book" src="/libro.jpg" alt="Cover of El Método Cabello Saludable by Yeney López-Pérez"/><span className="botanical one">⌇</span><span className="botanical two">⌇</span></div></div></section>
    <section className="intro wrap" id="method"><div><p className="eyebrow">A complete Spanish-language guide</p><h2>Understand, care for, and transform your hair from the roots.</h2></div><div className="introText"><p><strong>El Método Cabello Saludable</strong> is a practical guide that helps you understand your hair, build a routine that makes sense for you, and make decisions with more knowledge, consistency, and patience.</p><p>It does not promise miracles or present a single routine as perfect for everyone. It helps you understand what your hair needs and why it may react differently to products, habits, and ingredients.</p></div></section>
    <section className="pillars wrap"><article><span>01</span><i>◌</i><h3>Understand</h3><p>Recognize your hair’s characteristics and learn to listen to what it needs.</p></article><article><span>02</span><i>♧</i><h3>Nourish</h3><p>Discover habits and ingredients that support hair health from the roots.</p></article><article><span>03</span><i>∞</i><h3>Transform</h3><p>Build a sustainable routine that celebrates your texture and authentic beauty.</p></article></section>
    <section className="inside wrap"><div><p className="eyebrow">What you will find</p><h2>Knowledge you can bring into your routine.</h2></div><div className="insideList"><p><b>01</b><span><strong>Get to know your hair</strong>Its structure, porosity, natural cycle, and the factors that affect its appearance.</span></p><p><b>02</b><span><strong>Care for it with intention</strong>Washing, hydration, conditioning, and ingredients explained in simple terms.</span></p><p><b>03</b><span><strong>Read its signals</strong>The difference between hair loss and breakage, plus tools for observing real changes.</span></p><p><b>04</b><span><strong>Put it into practice</strong>Accessible homemade recipes, scientific references, and a 90-day progress journal.</span></p></div></section>
    <section className="forYou"><div className="wrap"><p className="eyebrow light">This book is for you if…</p><div className="forGrid"><h2>You want to stop guessing and start understanding.</h2><ul><li>You have tried many products without knowing what your hair actually needs.</li><li>You want to tell hair loss from breakage and recognize your hair’s signals.</li><li>You want a realistic routine for dry, curly, straight, color-treated, or damaged hair.</li><li>You prefer to move forward with knowledge, patience, and a record of your progress.</li></ul></div></div></section>
    <section className="quoteBand"><div className="wrap quoteGrid"><img src="/cabello.jpg" alt="Yeney’s long, healthy hair"/><blockquote><span>“</span><p>When you learn to care for your hair with knowledge and love, more than its appearance changes. The way you see yourself changes too.</p><cite>— Yeney López-Pérez</cite></blockquote></div></section>
    <section className="author wrap" id="author"><div className="authorPhoto"><img src="/yeney-home.jpg" alt="Yeney López-Pérez, author of El Método Cabello Saludable"/><span>Author<br/>& guide</span></div><div className="authorCopy"><p className="eyebrow">Meet the author</p><h2>Yeney<br/>López-Pérez</h2><p className="authorLead">Content creator with a passion for hair care.</p><p>After years of research and trial and error, Yeney transformed her own hair. In the book, she also shares her personal experience with hair loss associated with hypothyroidism, clearly presented as an individual experience and kept separate from information supported by scientific evidence.</p><p>Her purpose is to help you leave guesswork behind and build a routine with knowledge, intention, and self-love.</p></div></section>
    <section className="faq wrap" id="questions"><div><p className="eyebrow">Frequently asked questions</p><h2>Before you begin.</h2><p className="faqNote">The content is educational and does not replace evaluation or advice from a healthcare professional.</p></div><div className="faqItems"><details open><summary>Does the book propose one routine for everyone?</summary><p>No. It helps you observe your hair’s characteristics and adapt your decisions to its needs.</p></details><details><summary>Does it include practical recipes and routines?</summary><p>Yes. It includes care habits, ingredients, and accessible homemade recipes explained clearly.</p></details><details><summary>How does the 90-day journal help?</summary><p>It lets you record habits, changes, and results so you can adjust your routine with greater intention.</p></details><details><summary>What formats are available?</summary><p>It is available on Amazon as a printed paperback and Kindle edition, and on Google Play Books as an Ebook.</p></details></div></section>
    <section className="bookCta"><div className="wrap ctaGrid"><div><p className="eyebrow light">Your new chapter begins here</p><h2>Your hair is life. Care for it from the roots.</h2><p>It is not about having perfect hair. It is about knowing it, caring for it, and learning to enjoy it.</p><PurchaseButtons lang="en"/></div><img src="/libro-portada.png" alt="El Método Cabello Saludable, available on Amazon and Google Play Books"/></div></section>
    <Footer lang="en"/>
  </main>;
}
